version: "3"
services:
  app:
    build: .
    networks:
      - devShopmeDb
    volumes:
      - devShopmeDb:/var/lib/devShopmedb
    depends_on:
      - mysqlDevDb
    environment:
      - DATABASE_URL_DEV=jdbc:mysql://mysqlDevDb:3306/devShopme
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root

  mysqlDevDb:
    image: mysql:latest
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - devShopmeDb
    volumes:
      - devShopmeDb:/var/lib/devShopmedb

networks:
  devShopmeDb:
volumes:
  devShopmeDb:
    driver: local

